name: Build Docs on [LIVE-TEST]
on: [push]
permissions:
  contents: write
jobs:
  build-docs:
    if: ${{ contains(github.event.head_commit.message, '[LIVE-TEST]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Build docs
        run: npm run build:docs
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Set up PAT for pushing
        run: |
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/FranciscoRissox/react-workflow.git
      - name: Commit message
        run: git commit -am "Build docs"
      - name: Push changes
        run: git push