name: Build Docs on [LIVE-TEST]
on: 
    push:
        branches:
            - live-test
permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Build docs
        run: npm run build
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Set up PAT for pushing
        run: |
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/FranciscoRissox/react-workflow.git
      - name: Commit message
        run: |
            git add -f docs/
            git commit -am "Build docs"
      - name: Push changes
        run: git push