name: Build Docs on [LIVE-TEST]
on: [push]

jobs:
  build-docs:
    if: ${{ contains(github.event.head_commit.message, '[LIVE-TEST]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
      - name: Build docs
        run: npm run build:docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs